<?php
class ModelExtensionThemeSpeedy extends Model {
    public function install() {
        $this->db->query("CREATE TABLE `oc_product_video` (
        `product_video_id` int(11) NOT NULL,
        `product_id` int(11) NOT NULL,
        `video` varchar(255) DEFAULT NULL,
        `sort_order` int(3) NOT NULL DEFAULT 0,
        PRIMARY KEY (`product_video_id`),
        KEY `product_id` (`product_id`)
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8;");
        $this->db->query("CREATE TABLE IF NOT EXISTS `oc_megamenuvh` (
        `megamenu_id` int(11) NOT NULL AUTO_INCREMENT,
        `namemenu` text NOT NULL,
        `additional_menu` varchar(45) NOT NULL,
        `link` text NOT NULL,
        `menu_type` varchar(45) NOT NULL,
        `status` tinyint(1) NOT NULL DEFAULT '1',
        `sticker_parent` varchar(255) NOT NULL,
        `sticker_parent_bg` varchar(255) NOT NULL,
        `spctext` varchar(255) NOT NULL,
        `sort_menu` int(3) NOT NULL DEFAULT '0',
        `image` varchar(255) NOT NULL,
        `image_hover` varchar(255) NOT NULL,
        `informations_list` longtext NOT NULL,
        `manufacturers_setting` longtext NOT NULL,
        `products_setting` longtext NOT NULL,
        `link_setting` tinyint(1) NOT NULL,
        `category_setting` longtext NOT NULL,
        `html_setting` longtext NOT NULL,
        `freelinks_setting` longtext NOT NULL,
        `use_add_html` tinyint(1) NOT NULL,
        `add_html` longtext NOT NULL,
        PRIMARY KEY (`megamenu_id`)
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;");
        $this->db->query("INSERT IGNORE INTO `oc_extension` (`extension_id`, `type`, `code`) VALUES
        (1001, 'module', 'speedy_banner_top'),
        (1002, 'module', 'speedy_advantages'),
        (1003, 'module', 'speedy_banner_main'),
        (1004, 'module', 'speedy_banner_product'),
        (1012, 'module', 'speedy_menu'),
        (1013, 'module', 'speedy_categorywall'),
        (1014, 'module', 'speedy_buyoneclick'),
        (1015, 'module', 'speedy_quick_view'),
        (1016, 'module', 'speedy_carousel');");
        $this->db->query("INSERT IGNORE INTO `oc_module` (`module_id`, `name`, `code`, `setting`) VALUES
        (10035, 'Главная', 'speedy_carousel', '{\"name\":\"Главная\",\"banner_id\":\"8\",\"width\":\"130\",\"height\":\"130\",\"arrows\":\"0\",\"autoplay\":\"1\",\"autoplay_time\":\"2000\",\"status\":\"1\"}'),
        (10021, 'Главная', 'speedy_advantages', '{\"name\":\"Главная\",\"module_description\":{\"3\":{\"title\":\"\\Переваги\",\"blocks\":[{\"image\":\"catalog\\/edges\\/shipping.svg\",\"title\":\"Безкоштовна доставка\",\"description\":\"Безкоштовна доставка від 1000 грн\"},{\"image\":\"catalog\\/edges\\/bonus.svg\",\"title\":\"Бонуси за покупку\",\"description\":\"Бонуси за покупку на Ваш рахунок\"},{\"image\":\"catalog\\/edges\\/return.svg\",\"title\":\"Повернення та обмін\",\"description\":\"Повернення та обмін протягом 14 днів\"},{\"image\":\"catalog\\/edges\\/certificate.svg\",\"title\":\"Сертифікацiя\",\"description\":\"Сертифіковані товари\"}]},\"1\":{\"title\":\"Преимущества\",\"blocks\":{\"4\":{\"image\":\"catalog\\/edges\\/shipping.svg\",\"title\":\"Бесплатная доставка\",\"description\":\"Бесплатная доставка от 1000 грн\"},\"5\":{\"image\":\"catalog\\/edges\\/bonus.svg\",\"title\":\"Бонусы за покупку\",\"description\":\"Бонусы за покупку на Ваш счет\"},\"6\":{\"image\":\"catalog\\/edges\\/return.svg\",\"title\":\"Возврат и обмен\",\"description\":\"Возврат и обмен в течении 14 дней\"},\"7\":{\"image\":\"catalog\\/edges\\/certificate.svg\",\"title\":\"Сертификация\",\"description\":\"Сертифицированные товары\"}}},\"2\":{\"title\":\"Advantages\",\"blocks\":{\"8\":{\"image\":\"catalog\\/edges\\/shipping.svg\",\"title\":\"Free delivery\",\"description\":\"Free delivery from 1000 UAH\"},\"9\":{\"image\":\"catalog\\/edges\\/bonus.svg\",\"title\":\"Bonuses for the purchase\",\"description\":\"Bonuses for the purchase to your account\"},\"10\":{\"image\":\"catalog\\/edges\\/return.svg\",\"title\":\"Return and exchange\",\"description\":\"Return and exchange within 14 days\"},\"11\":{\"image\":\"catalog\\/edges\\/certificate.svg\",\"title\":\"Certification\",\"description\":\"Certified Products\"}}}},\"column\":\"4\",\"align\":\"left\",\"width\":\"50\",\"height\":\"50\",\"status\":\"1\"}'),
        (10036, 'Apple - 5 товарів', 'speedy_banner_product', '{\"status\":\"1\",\"name\":\"Apple - 5 товарів\",\"type\":\"carousel\",\"column\":\"3\",\"width\":\"280\",\"height\":\"280\",\"banner_description\":{\"3\":{\"blocks\":[{\"image\":\"catalog\\/demo\\/module_smart_products\\/iphone_15_pro.png\",\"background_color\":\"#fff2cc\",\"title\":\"iPhone 15 Pro Max\",\"link\":\"iphone-15-pro-max\",\"button_type\":\"1\",\"button_text\":\"Придбати\",\"sticker\":\"Хіт продажу\",\"price\":\"від 57 999 грн.\"},{\"image\":\"catalog\\/demo\\/module_smart_products\\/ipad_109.png\",\"background_color\":\"#f4cccc\",\"title\":\"iPad 10.9&quot;\",\"link\":\"ipad-10\",\"button_type\":\"0\",\"button_text\":\"Замовити\",\"sticker\":\"Новинка\",\"price\":\"від 19 999 грн.\"},{\"image\":\"catalog\\/demo\\/module_smart_products\\/macbook_pro_16.png\",\"background_color\":\"#d9ead3\",\"title\":\"MacBook Air 15&quot; M2\",\"link\":\"macbook-air\",\"button_type\":\"1\",\"button_text\":\"Придбати\",\"sticker\":\"Популярний\",\"price\":\"від 55 499 грн.\"},{\"image\":\"catalog\\/demo\\/module_smart_products\\/ultra_watch.png\",\"background_color\":\"#cfe2f3\",\"title\":\"Ultra Watch 2\",\"link\":\"test\",\"button_type\":\"0\",\"button_text\":\"Подивитись\",\"sticker\":\"Акційна ціна\",\"price\":\"від 55 499 грн.\"},{\"image\":\"catalog\\/demo\\/module_smart_products\\/earpods_pro.png\",\"background_color\":\"#d9d2e9\",\"title\":\"AirPods Pro 2\",\"link\":\"test\",\"button_type\":\"1\",\"button_text\":\"Придбати\",\"sticker\":\"-25% від ціни\",\"price\":\"від 55 499 грн.\"}]},\"1\":{\"blocks\":{\"5\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/iphone_15_pro.png\",\"background_color\":\"#fff2cc\",\"title\":\"iPhone 15 Pro Max\",\"link\":\"iphone-15-pro-max-ru\",\"button_type\":\"1\",\"button_text\":\"Купить\",\"sticker\":\"Хит продаж\",\"price\":\"от 57 999 грн.\"},\"6\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/ipad_109.png\",\"background_color\":\"#f4cccc\",\"title\":\"iPad 10.9&quot;\",\"link\":\"ipad-10-ru\",\"button_type\":\"0\",\"button_text\":\"Заказать\",\"sticker\":\"Новинка\",\"price\":\"от 19 999 грн.\"},\"7\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/macbook_pro_16.png\",\"background_color\":\"#d9ead3\",\"title\":\"MacBook Air 15&quot; M2\",\"link\":\"macbook-air-ru\",\"button_type\":\"1\",\"button_text\":\"Купить\",\"sticker\":\"Популярный\",\"price\":\"от 55 499 грн.\"},\"8\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/ultra_watch.png\",\"background_color\":\"#cfe2f3\",\"title\":\"Ultra Watch 2\",\"link\":\"test-ru\",\"button_type\":\"0\",\"button_text\":\"Посмотреть\",\"sticker\":\"Акционная цена\",\"price\":\"от 55 499 грн.\"},\"9\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/earpods_pro.png\",\"background_color\":\"#d9d2e9\",\"title\":\"AirPods Pro 2\",\"link\":\"test-ru\",\"button_type\":\"1\",\"button_text\":\"Приобрести\",\"sticker\":\"-25% от цены\",\"price\":\"от 55 499 грн.\"}}},\"2\":{\"blocks\":{\"10\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/iphone_15_pro.png\",\"background_color\":\"#fff2cc\",\"title\":\"iPhone 15 Pro Max\",\"link\":\"iphone-15-pro-max-en\",\"button_type\":\"1\",\"button_text\":\"Buy\",\"sticker\":\"Bestseller\",\"price\":\"from 57 999 UAH\"},\"11\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/ipad_109.png\",\"background_color\":\"#f4cccc\",\"title\":\"iPad 10.9&quot;\",\"link\":\"ipad-10-en\",\"button_type\":\"0\",\"button_text\":\"Order\",\"sticker\":\"New\",\"price\":\"from 19 999 UAH\"},\"12\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/macbook_pro_16.png\",\"background_color\":\"#d9ead3\",\"title\":\"MacBook Air 15&quot; M2\",\"link\":\"macbook-air-en\",\"button_type\":\"1\",\"button_text\":\"Buy\",\"sticker\":\"Popular\",\"price\":\"from 55 499 UAH\"},\"13\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/ultra_watch.png\",\"background_color\":\"#cfe2f3\",\"title\":\"Ultra Watch 2\",\"link\":\"test-en\",\"button_type\":\"0\",\"button_text\":\"Look\",\"sticker\":\"Promo price\",\"price\":\"from 55 499 UAH\"},\"14\":{\"image\":\"catalog\\/demo\\/module_smart_products\\/earpods_pro.png\",\"background_color\":\"#d9d2e9\",\"title\":\"AirPods Pro 2\",\"link\":\"test-en\",\"button_type\":\"1\",\"button_text\":\"Buy\",\"sticker\":\"-25% of the price\",\"price\":\"from 55 499 UAH\"}}}}}'),
        (10031, 'Главная', 'speedy_banner_main', '{\"status\":\"1\",\"name\":\"Главная\",\"container\":\"adaptive\",\"type\":\"slider\",\"slider_type\":\"image_and_text\",\"width_slider_pc\":\"1470\",\"height_slider_pc\":\"500\",\"width_slider_mob\":\"640\",\"height_slider_mob\":\"1024\",\"width_carousel\":\"640\",\"height_carousel\":\"1024\",\"carousel_items\":\"5\",\"autoplay\":\"0\",\"autoplay_time\":\"2000\",\"banner_description\":{\"3\":{\"blocks\":[{\"image\":\"catalog\\/demo\\/banners\\/1470x500_1_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link\":\"test-ua\"},{\"image\":\"catalog\\/demo\\/banners\\/1470x500_2_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link\":\"test-ua\"}]},\"1\":{\"blocks\":{\"2\":{\"image\":\"catalog\\/demo\\/banners\\/1470x500_1_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link\":\"test-ru\"},\"3\":{\"image\":\"catalog\\/demo\\/banners\\/1470x500_2_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link\":\"test-ru\"},\"4\":{\"image\":\"\",\"image_mob\":\"\",\"link\":\"\"}}},\"2\":{\"blocks\":{\"5\":{\"image\":\"catalog\\/demo\\/banners\\/1470x500_1_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link\":\"test-en\"},\"6\":{\"image\":\"catalog\\/demo\\/banners\\/1470x500_2_banner.png\",\"image_mob\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link\":\"test-en\"}}}},\"banner_it_description\":{\"3\":{\"blocks\":[{\"it_image\":\"catalog\\/demo\\/banners\\/iphone_14_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/iphone_14_pro_mob.png\",\"it_link\":\"\\/test\",\"it_position\":\"0\",\"it_title\":\"Apple iPhone 14 Pro\",\"it_description\":\"Революційні функції безпеки розроблені для порятунку життя. Інноваційна 48-мегапіксельна камера для приголомшливої деталізації. Все працює на новітньому чіпі для смартфонів.\",\"it_button_text\":\"Придбати у нас\",\"it_background_color\":\"#f2f8ff\"},{\"it_image\":\"catalog\\/demo\\/banners\\/macbook_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/macbook_pro_mob.png\",\"it_link\":\"\\/\",\"it_position\":\"1\",\"it_title\":\"Apple MacBook Pro\",\"it_description\":\"Справжній атлант продуктивності та багатозадачності. Дивовижні показники потужності, збільшена автономність, ультраяскравий екран та широка різноманітність функціональних портів не залишать байдужим нікого.\",\"it_button_text\":\"Купити зі знижкою 25%\",\"it_background_color\":\"#051832\"}]},\"1\":{\"blocks\":{\"2\":{\"it_image\":\"catalog\\/demo\\/banners\\/iphone_14_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/iphone_14_pro_mob.png\",\"it_link\":\"\\/test\",\"it_position\":\"0\",\"it_title\":\"Apple iPhone 14 Pro\",\"it_description\":\"Революционные функции безопасности, разработанные для спасения жизни. Инновационная 48-мегапиксельная камера для потрясающей детализации. Все работает на новейшем чипе для смартфонов.\",\"it_button_text\":\"Приобрести у нас\",\"it_background_color\":\"#f2f8ff\"},\"3\":{\"it_image\":\"catalog\\/demo\\/banners\\/macbook_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/macbook_pro_mob.png\",\"it_link\":\"\\/\",\"it_position\":\"1\",\"it_title\":\"Apple MacBook Pro\",\"it_description\":\"Настоящий атлант продуктивности и многозадачности. Удивительные показатели мощности, увеличенная автономность, ультраяркий экран и широкое разнообразие функциональных портов не оставят равнодушным никого.\",\"it_button_text\":\"Купить со скидкой 25%\",\"it_background_color\":\"#051832\"}}},\"2\":{\"blocks\":{\"4\":{\"it_image\":\"catalog\\/demo\\/banners\\/iphone_14_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/iphone_14_pro_mob.png\",\"it_link\":\"\\/test\",\"it_position\":\"0\",\"it_title\":\"Apple iPhone 14 Pro\",\"it_description\":\"Revolutionary safety features designed to save lives. Innovative 48MP camera for stunning detail. Everything runs on the latest smartphone chip.\",\"it_button_text\":\"Buy from us\",\"it_background_color\":\"#f2f8ff\"},\"5\":{\"it_image\":\"catalog\\/demo\\/banners\\/macbook_pro_pc.png\",\"it_image_mob\":\"catalog\\/demo\\/banners\\/macbook_pro_mob.png\",\"it_link\":\"\\/\",\"it_position\":\"1\",\"it_title\":\"Apple MacBook Pro\",\"it_description\":\"A true atlas of productivity and multitasking. Amazing power ratings, increased battery life, an ultra-bright screen and a wide variety of functional ports will not leave anyone indifferent.\",\"it_button_text\":\"Buy with 25% discount\",\"it_background_color\":\"#051832\"}}}},\"banner_carousel_description\":{\"3\":{\"blocks\":[{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link_carousel\":\"test-ua\"},{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link_carousel\":\"test-ua\"},{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_3_banner.png\",\"link_carousel\":\"test-ua\"},{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_4_banner.png\",\"link_carousel\":\"test-ua\"},{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_5_banner.png\",\"link_carousel\":\"test-ua\"},{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_6_banner.png\",\"link_carousel\":\"test-ua\"}]},\"1\":{\"blocks\":{\"6\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link_carousel\":\"test-ru\"},\"7\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link_carousel\":\"test-ru\"},\"8\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_3_banner.png\",\"link_carousel\":\"test-ru\"},\"9\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_4_banner.png\",\"link_carousel\":\"test-ru\"},\"10\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_5_banner.png\",\"link_carousel\":\"test-ru\"},\"11\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_6_banner.png\",\"link_carousel\":\"test-ru\"}}},\"2\":{\"blocks\":{\"12\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_1_banner.png\",\"link_carousel\":\"test-en\"},\"13\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_2_banner.png\",\"link_carousel\":\"test-en\"},\"14\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_3_banner.png\",\"link_carousel\":\"test-en\"},\"15\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_4_banner.png\",\"link_carousel\":\"test-en\"},\"16\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_5_banner.png\",\"link_carousel\":\"test-en\"},\"17\":{\"image_carousel\":\"catalog\\/demo\\/banners\\/640x1024_6_banner.png\",\"link_carousel\":\"test-en\"}}}}}');");
        $this->db->query("INSERT IGNORE INTO `oc_setting` (`setting_id`, `store_id`, `code`, `key`, `value`, `serialized`) VALUES
        (0, 0, 'module_speedy_categorywall', 'module_speedy_categorywall_status', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_descript', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_specifications', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_comparison', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_bookmarks', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_status', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_btnquick', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_rewards', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_reviews', '1', 0),
        (0, 0, 'module_speedy_quick_view', 'module_speedy_quick_view_brand', '1', 0),
        (0, 0, 'module_speedy_buyoneclick', 'module_speedy_buyoneclick_status', '1', 0),
        (0, 0, 'buyoneclick', 'buyoneclick', '{\"name\":{\"3\":\"Купити в 1 клiк\",\"1\":\"Купить в 1 клик\",\"2\":\"Buy in 1 click\"},\"success_type\":\"0\",\"success_field\":{\"3\":\"Дякую за ваше замовлення!\",\"1\":\"Спасибо за ваш заказ!\",\"2\":\"Thank you for your order!\"},\"field1_status\":\"1\",\"field2_status\":\"1\",\"field3_status\":\"1\",\"field4_status\":\"0\",\"agree_status\":\"0\",\"option_status\":\"0\",\"validation_type\":\"0\",\"style_status\":\"0\",\"stock_status\":\"1\",\"status_product\":\"1\",\"status_category\":\"1\",\"status_module\":\"1\",\"smsru_api\":\"\",\"smsru_login\":\"\",\"smsru_password\":\"\",\"smsru_number\":\"\",\"smsru_name\":\"\",\"smsru_admin_sms\":\"\",\"smsru_admin_status\":\"0\",\"smsru_client_sms\":\"\",\"smsru_client_status\":\"0\",\"smscua_login\":\"\",\"smscua_password\":\"\",\"smscua_number\":\"\",\"smscua_name\":\"\",\"smscua_admin_sms\":\"\",\"smscua_admin_status\":\"0\",\"smscua_client_sms\":\"\",\"smscua_client_status\":\"0\",\"ya_counter\":\"\",\"ya_identificator\":\"\",\"ya_identificator_send\":\"\",\"ya_identificator_success\":\"\",\"ya_status\":\"0\",\"google_category_btn\":\"\",\"google_action_btn\":\"\",\"google_category_send\":\"\",\"google_action_send\":\"\",\"google_category_success\":\"\",\"google_action_success\":\"\",\"google_status\":\"0\",\"exan_status\":\"0\"}', 1),
        (0, 0, 'module_speedy_menu', 'module_speedy_menu_status', '1', 0),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_width', '1000', 0),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_height', '60', 0),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_text', '{\"3\":\"Знижки на товари до 67%\",\"1\":\"Скидки на все товары до 67%\",\"2\":\"Discounts on all products up to 67%\"}', 1),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_background', '#2a3b4c', 0),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_status', '1', 0),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_link', '{\"3\":\"test\",\"1\":\"test-ru\",\"2\":\"test-en\"}', 1),
        (0, 0, 'module_speedy_banner_top', 'module_speedy_banner_top_image', 'catalog/demo/banners/1000x60_banner_top_no_text.png', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_messenger_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_modal_cookie_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_location_height', '375', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_cart_sidebar_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_cart_sidebar_position', 'right', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_cart_sidebar_clear_status', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_modal_cookie_description', '{\"3\":\"&lt;p&gt;Я даю згоду на використання Cookie у моєму браузері.&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Я даю согласие на использование «Cookie» в моём браузере.&lt;br&gt;&lt;\\/p&gt;\",\"2\":\"&lt;p&gt;I consent to the use of cookies in my browser.&lt;br&gt;&lt;\\/p&gt;\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_image_location_width', '500', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_cart_height', '47', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_cart_width', '47', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_m_menu_additional_link', '{\"3\":[{\"title\":\"Акційні товари\",\"link\":\"specials\",\"image\":\"catalog\\/menu_icons\\/specials.svg\"},{\"title\":\"Бренди\",\"link\":\"brands\",\"image\":\"catalog\\/menu_icons\\/brand.svg\"}],\"1\":{\"2\":{\"title\":\"Акционные товары\",\"link\":\"ru-specials\",\"image\":\"catalog\\/menu_icons\\/specials.svg\"},\"3\":{\"title\":\"Бренды\",\"link\":\"ru-brands\",\"image\":\"catalog\\/menu_icons\\/brand.svg\"}},\"2\":{\"4\":{\"title\":\"Promotional items\",\"link\":\"en-specials\",\"image\":\"catalog\\/menu_icons\\/specials.svg\"},\"5\":{\"title\":\"Brands\",\"link\":\"en-brands\",\"image\":\"catalog\\/menu_icons\\/brand.svg\"}}}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_arrows', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit_xs', '2', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit_sm', '2', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit_md', '3', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit_xl', '4', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit_lg', '3', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_slider_limit', '5', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_products_type', 'slider', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_wishlist_width', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_wishlist_height', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_compare_width', '90', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_compare_height', '90', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_related_height', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_related_width', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_additional_height', '74', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_additional_width', '74', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_product_height', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_product_width', '360', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_popup_height', '700', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_popup_width', '700', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_thumb_height', '500', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_thumb_width', '500', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_manufacturer_height', '80', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_manufacturer_width', '80', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_image_category_height', '80', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_contacts_contact_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_bottombar_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_checklang_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_checklang_type', 'ua_lang', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_hot_name', '{\"3\":\"Популярний\",\"1\":\"Популярный\",\"2\":\"Popular\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_image_category_width', '80', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_contacts_shops_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_checkout_fixed_cart', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_checkout_label_view', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_register_rules', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_register_rules_description', '{\"3\":\"Реєстрація облікового запису передбачає, що ви вже прочитали умови угоди, правила повернення товару, а також даєте згоду на використання cookie вашого браузера.\",\"1\":\"Регистрация аккаунта подразумевает, что вы уже прочитали условия соглашения, правила возврата товара, а также даёте согласие на использования Cookie вашего браузера.\",\"2\":\"&lt;p&gt;Registering an account implies that you have already read the terms of the agreement, the rules for returning goods, and also agree to the use of Cookies in your browser.&lt;br&gt;&lt;\\/p&gt;\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_video_status', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_video_additional', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_video_tab', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_hot_count', '1000', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_hot_background', '#3d85c6', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_hot_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_sale_count', '100', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_sale_name', '{\"3\":\"Хіт продажу\",\"1\":\"Хит продаж\",\"2\":\"Bestseller\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_special_name', '{\"3\":\"Зі знижкою\",\"1\":\"Со скидкой\",\"2\":\"Discount\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_sale_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_sale_background', '#cc0000', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_special_background', '#e69138', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_new_name', '{\"3\":\"Новинка\",\"1\":\"Новинка\",\"2\":\"New\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_new_days', '15', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_special_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_new_background', '#6aa84f', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_payment_item', '{\"3\":[{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/p24.svg\"},{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/mono.svg\"},{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/apay.svg\"},{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/gpay.svg\"}],\"1\":{\"4\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/p24.svg\"},\"5\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/mono.svg\"},\"6\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/apay.svg\"},\"7\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/gpay.svg\"}},\"2\":{\"8\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/p24.svg\"},\"9\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/mono.svg\"},\"10\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/apay.svg\"},\"11\":{\"title\":\"\",\"image\":\"catalog\\/payment_product\\/gpay.svg\"}}}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_questions_status', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_text_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sticker_new_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_guarantee_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_guarantee_description', '{\"3\":\"&lt;p&gt;Відповідно до Закону України «Про захист прав споживачів», Ви можете повернути або обміняти товар протягом 14 днів з моменту покупки&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;В соответствии с Законом Украины «О защите прав потребителей» Вы можете вернуть или обменять товар в течение 14 дней с момента покупки&lt;br&gt;&lt;\\/p&gt;\",\"2\":\"&lt;p&gt;In accordance with the Law of Ukraine &quot;On Protection of Consumer Rights&quot;, you can return or exchange goods within 14 days from the date of purchase&lt;br&gt;&lt;\\/p&gt;\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_edges_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_edges_item', '{\"3\":[{\"title\":\"Безкоштовна доставка від 1000 грн\",\"image\":\"catalog\\/edges\\/shipping.svg\"},{\"title\":\"Бонуси за покупку на Ваш рахунок\",\"image\":\"catalog\\/edges\\/bonus.svg\"},{\"title\":\"Повернення та обмін протягом 14 днів\",\"image\":\"catalog\\/edges\\/return.svg\"},{\"title\":\"Сертифіковані товари\",\"image\":\"catalog\\/edges\\/\\certificate.svg\"}],\"1\":{\"4\":{\"title\":\"Бесплатная доставка от 1000 грн\",\"image\":\"catalog\\/edges\\/shipping.svg\"},\"5\":{\"title\":\"Бонусы за покупку на Ваш счет\",\"image\":\"catalog\\/edges\\/bonus.svg\"},\"6\":{\"title\":\"Возврат и обмен в течении 14 дней\",\"image\":\"catalog\\/edges\\/return.svg\"},\"7\":{\"title\":\"Сертифицированные товары\",\"image\":\"catalog\\/edges\\/\\certificate.svg\"}},\"2\":{\"8\":{\"title\":\"Free delivery from 1000 UAH\",\"image\":\"catalog\\/edges\\/shipping.svg\"},\"9\":{\"title\":\"Bonuses for the purchase to your account\",\"image\":\"catalog\\/edges\\/bonus.svg\"},\"10\":{\"title\":\"Return and exchange within 14 days\",\"image\":\"catalog\\/edges\\/return.svg\"},\"11\":{\"title\":\"Certified Products\",\"image\":\"catalog\\/edges\\/\\certificate.svg\"}}}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_shipping_item', '{\"3\":[{\"title\":\"\",\"image\":\"catalog\\/shipping\\/np.svg\"},{\"title\":\"\",\"image\":\"catalog\\/shipping\\/up.svg\"},{\"title\":\"Самовивіз (м. Київ)\",\"image\":\"catalog\\/shipping\\/warehouse.svg\"}],\"1\":{\"3\":{\"title\":\"\",\"image\":\"catalog\\/shipping\\/np.svg\"},\"4\":{\"title\":\"\",\"image\":\"catalog\\/shipping\\/up.svg\"},\"5\":{\"title\":\"Самовывоз (г. Киев)\",\"image\":\"catalog\\/shipping\\/warehouse.svg\"}},\"2\":{\"6\":{\"title\":\"\",\"image\":\"catalog\\/shipping\\/np.svg\"},\"7\":{\"title\":\"\",\"image\":\"catalog\\/shipping\\/up.svg\"},\"8\":{\"title\":\"Pickup (Kyiv city)\",\"image\":\"catalog\\/shipping\\/warehouse.svg\"}}}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_payment_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_payment_description', '{\"3\":\"&lt;p&gt;Ви можете безпечно оплатити замовлення онлайн або при отриманні&lt;br&gt;&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Вы можете безопасно оплатить заказ онлайн или при получении&lt;\\/p&gt;\",\"2\":\"&lt;p&gt;You can securely pay for your order online or upon receipt&lt;br&gt;&lt;\\/p&gt;\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_fixed_scroll_thumbs', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_description_position', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_manufacturer', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_model', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_sku', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_stock', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_purchased_product', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_viewed', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_home_catalog_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_fixed_nav_tabs', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_button_cart', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_special_price_type', 'percent', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_bottom_bar', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_shipping_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_shipping_description', '{\"3\":\"&lt;p&gt;Доставка нашої продукції по всій Україні у стислий термін у день замовлення!&lt;br&gt;&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Доставка нашей продукции по всей Украине в сжатые сроки в день заказа!&lt;\\/p&gt;\",\"2\":\"&lt;p&gt;Delivery of our products throughout Ukraine in a short time on the day of order!&lt;br&gt;&lt;\\/p&gt;\"}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_product_limit', '15', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_button_cart', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_stock', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_attribute_groups', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_quantity', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_model', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_description', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_description_position', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_category_refine_img', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_stickers_image', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_catalog_stickers_text', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_product_description_length', '100', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_code_footer_js', '', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_code_header_js', '', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_code_header_css', '', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_code_footer_js_link', '', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_code_header_css_link', '', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_xs', '100', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_type_xs', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_sm', '100', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_type_sm', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_md', '90', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_type_md', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_type_lg', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_lg', '90', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width_type', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_adaptive_container_width', '1470', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_push_alert_type', 'alert', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_payment', '[{\"image\":\"catalog\\/payment\\/mono.svg\",\"sort_order\":\"2\"},{\"image\":\"catalog\\/payment\\/p24.svg\",\"sort_order\":\"1\"},{\"image\":\"catalog\\/payment\\/apay.svg\",\"sort_order\":\"3\"},{\"image\":\"catalog\\/payment\\/gpay.svg\",\"sort_order\":\"4\"}]', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_push_cart_alert_type', 'alert', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_checklang_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_widgets_checklang_type', 'ua_lang', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_payments_status', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_socials', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_address', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_map', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_map_code', '&lt;iframe src=&quot;https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2540.364065519159!2d30.514344699999995!3d50.4529449!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4ce5b9f4b16d3%3A0x77e535b9b78d5e5e!2z0YPQuy4g0JLQu9Cw0LTQuNC80LjRgNGB0LrQsNGPLCAyNCwg0JrQuNC10LIsIDAyMDAw!5e0!3m2!1sru!2sua!4v1699970570102!5m2!1sru!2sua&quot; width=&quot;600&quot; height=&quot;450&quot; style=&quot;border:0;&quot; allowfullscreen=&quot;&quot; loading=&quot;lazy&quot; referrerpolicy=&quot;no-referrer-when-downgrade&quot;&gt;&lt;/iframe&gt;', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_menu_link', '{\"3\":[{\"title\":\"Контакти\",\"link\":\"contact-us\"}],\"1\":{\"1\":{\"title\":\"Контакты\",\"link\":\"ru-contact-us\"}},\"2\":{\"2\":{\"title\":\"Contacts\",\"link\":\"en-contact-us\"}}}', 1),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_email', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_messengers', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_phones', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_footer_menu_lenght', '10', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_email', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_open', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_messengers', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_phones', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_account', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_wishlist', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_compare', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_currency', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_language', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_font_size', '14', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_font_family', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_background_payments_color', '#07141f', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_background_footer_color', '#081e2e', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_header_color', 'white', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_special_color', '#f28400', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_background_top_color', '#f8f9fa', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_main_color', '#41ade3', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_main_color_2', '#23a1cd', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_main_color_3', '#0e89ca', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_background_color', '#f7f8f9', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_scheme_color_edit', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_scheme_color', '1', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_status', '0', 0),
        (0, 0, 'theme_speedy', 'theme_speedy_directory', 'speedy', 0);");
    }
}